version: "3.0"
name: "raft-atm"
services:
  # gateway:
  #   image: nginx
  #   tty: true
  # stdin_open: true
  # container_name: gateway
  #   volumes:
  #     - ./nginx/conf:/etc/nginx/conf.d
  #   ports:
  #     - 8080:80
  #   networks:
  #     - internal
  # volumes:
  # - ./db:/app/db
  #   environment:
  #     - COMPOSE_PROJECT_NAME

  atm-1:
    image: raft-atm/atm
    build: ./atm
    tty: true
    stdin_open: true
    container_name: atm-1
    hostname: atm-1
    networks:
      - internal
    volumes:
    - ./db:/app/db
    - ./journal:/app/journal
    - ./dump:/app/dump
    environment:
      - COMPOSE_PROJECT_NAME
      - REPLICA_NO=1
      - TOT_REPLICAS=${TOT_REPLICAS}
  
  atm-2:
    image: raft-atm/atm
    build: ./atm
    tty: true
    stdin_open: true
    container_name: atm-2
    hostname: atm-2
    networks:
      - internal
    volumes:
    - ./db:/app/db
    - ./journal:/app/journal
    - ./dump:/app/dump
    environment:
      - COMPOSE_PROJECT_NAME
      - REPLICA_NO=2
      - TOT_REPLICAS=${TOT_REPLICAS}
  
  atm-3:
    image: raft-atm/atm
    build: ./atm
    tty: true
    stdin_open: true
    container_name: atm-3
    hostname: atm-3
    networks:
      - internal
    volumes:
    - ./db:/app/db
    - ./journal:/app/journal
    - ./dump:/app/dump
    environment:
      - COMPOSE_PROJECT_NAME
      - REPLICA_NO=3
      - TOT_REPLICAS=${TOT_REPLICAS}

  # atm-4:
  #   image: raft-atm/atm
  #   build: ./atm
  #   tty: true
  #   stdin_open: true
  #   container_name: atm-4
  #   hostname: atm-4
  #   networks:
  #     - internal
  #   volumes:
  #   - ./db:/app/db
  #   - ./journal:/app/journal
  #   - ./dump:/app/dump
  #   environment:
  #     - COMPOSE_PROJECT_NAME
  #     - REPLICA_NO=4
  #     - TOT_REPLICAS=${TOT_REPLICAS}

  # atm-5:
  #   image: raft-atm/atm
  #   build: ./atm
  #   tty: true
  #   stdin_open: true
  #   container_name: atm-5
  #   hostname: atm-5
  #   networks:
  #     - internal
  #   volumes:
  #   - ./db:/app/db
  #   - ./journal:/app/journal
  #   - ./dump:/app/dump
  #   environment:
  #     - COMPOSE_PROJECT_NAME
  #     - REPLICA_NO=5
  #     - TOT_REPLICAS=${TOT_REPLICAS}

networks:
  internal:
  

    